name: Manual trigger
on:
  workflow_dispatch:
    inputs:
      message:
        description: message to echo
        required: true
        type: string

jobs:
  message:
    uses: mllano20/python-gql-test/echo-once@main
    with:
      message: ${{ inputs.message }}
